config/routes.rb
Rails.application.routes.draw do
 
  scope module: :public do
    #URLはpublicを消したいのでpublicのルートはこの中に記述する
    #'指定したいURL' => 'コントローラー名#アクション名', as: 'ルートパス'
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'customers/show'
    get 'customers/information/edit' => 'customers#edit', as: 'customers/edit'
    get 'customers/unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers/update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customers/withdraw'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_item/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/complete' => 'orders#complete', as: 'orders/complete'
    post 'orders/confirm' => 'orders#confirm', as: 'orders/confirm'
    resources :orders, only: [:new, :index, :show, :create]
  end
  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:create, :index, :new, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions:      'admin/sessions'
}
devise_for :customers,skip: [:passwords], controllers: {
  sessions:      'public/sessions',
  registrations: 'public/registrations'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 def add_tax_price
   (self.price * 1.10).floor
 end
  
 def subtotal
      item.add_tax_price*amount
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  belongs_to :item
  belongs_to :customer
  
  def add_tax_price
   (self.price * 1.10).floor
  end
  
  def subtotal
      item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  has_one_attached :image
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def add_tax_price
   (self.price * 1.10).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  def add_tax_price
   (self.price * 1.10).floor
  end
  
  def subtotal
      item.add_tax_price*quantity
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save!
    redirect_to admin_genres_path
  end
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
   private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
   private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = 0
    @postage = 800
    @billing_amount = @postage + @total
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  protected
   def after_sign_in_path_for(resource)
     admin_root_path
   end
   
   def after_sign_out_path_for(resource)
     new_admin_session_path
   end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h1>

<p>会員ID<%= @customer.id %></p>

<%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>

<h4>氏名</h4>
<%= f.text_field :last_name %><%= f.text_field :first_name %>

<h4>フリガナ</h4>
<%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %>

<h4>郵便番号</h4>
<%= f.text_field :postal_code %>

<h4>住所</h4>
<%= f.text_field :address %>

<h4>電話番号</h4>
<%= f.text_field :telephone_number %>

<h4>メールアドレス</h4>
<%= f.text_field :email %>

<%= f.submit "変更を保存", class: "btn btn-success" %>

<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table border="1" rules="rows">
  <tbody>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td>
        <%= link_to admin_customer_path(customer.id) do %>
        <%= customer.last_name + customer.first_name %>
        <% end %>
        </td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_deleted == false %>
         <p class="text-success"><%= "有効" %></p>
        <% else %>
         <p class="text-muted"><%= "退会" %></p>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h1>

<p>会員ID<%= @customer.id %></p>
<p>氏名<%= @customer.last_name %><%= @customer.first_name %></p>
<p>フリガナ<%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>
<p>郵便番号<%= @customer.postal_code %></p>
<p>住所<%= @customer.address %></p>
<p>電話番号<%= @customer.telephone_number %></p>
<p>メールアドレス<%= @customer.email %></p>

<%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success" %>

<!--注文履歴一覧画面へのリンクを作成-->

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
<h4>ジャンル名</h4>
<%= f.text_field :name %>
<%= f.submit "変更を保存", class: "btn btn-success" %>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>
<!--ジャンル追加-->
<%= form_with model: @genre, url: admin_genres_path do |f| %>
<h4>ジャンル名</h4>
<%= f.text_field :name %>

<%= f.submit '新規登録', class: "btn btn-success" %>

<% end %>

<!--ジャンル一覧-->
<table border="1" style="border-collapse: collapse">
  <tr>
    <th>ジャンル</th>
  </tr>
 <% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
  </tr>
 <% end %>
</table>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>

<%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

<div class="field">
  <h4>商品画像</h4>
  <%= f.file_field :image %>
</div>

<div class="field">
  <h4>商品名</h4>
  <%= f.text_field :name %>
</div>

<div class="field">
  <h4>商品説明</h4>
  <%= f.text_area :introduction %>
</div>

<div class="field">
  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %>
</div>

<div class="field">
  <h4>税抜価格</h4>
  <%= f.text_field :price %>円
</div>

<%= f.submit "変更を保存", class: "btn btn-success" %>

<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td>
        <%= link_to admin_item_path(item.id) do %>
         <%= item.name %>
        <% end %>
      </td>
      <td><%= item.price.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
<h4>商品画像</h4>
<%= f.file_field :image, accept: "image/*" %>

<h4>商品名</h4>
<%= f.text_field :name %>

<h4>商品説明</h4>
<%= f.text_area :introduction %>

<h4>ジャンル</h4>
<%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>

<h4>税抜価格</h4>
<%= f.text_field :price %>円


<%= f.submit '新規登録', class: "btn btn-success" %>

<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>

<!--商品画像-->
<%= image_tag @item.get_image(200,200) %>

<p>商品名</p>
<%= @item.name %>

<p>商品説明</p>
<%= @item.introduction %>

<p>ジャンル</p>
<%= @item.genre.name %>

<p>税込価格(税抜価格)</p>
<%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>)円

<%= link_to '編集する', edit_admin_item_path, class: "btn btn-success" %>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>

<h4>購入者</h4>
<%= link_to admin_customer_path(@order.customer_id) do %>
<%= @order.customer.last_name + @order.customer.first_name %>
<% end %>

<h4>注文日</h4>
<%= @order.created_at.strftime('%Y/%m/%d') %>

<h4>配送先</h4>
〒<%= @order.postal_code %><%= @order.address %></br>
<%= @order.name %>

<h4>支払方法</h4>
<%= @order.payment_method_i18n %>

<table border="1" rules="rows">
  <tbody>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
    </tr>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= order_detail.price.to_s(:delimited) %></td>
      <td><%= order_detail.quantity %></td>
      <td><%= order_detail.subtotal.to_s(:delimited) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% @order_details.each do |order_detail| %>
 <% @total += order_detail.subtotal %>
<% end %>
<h4>商品合計</h4>
<%= @total.to_s(:delimited) %>円

<h4>送料</h4>
<%= @postage %>円

<h4>請求金額合計</h4>
<%= @order.billing_amount.to_s(:delimited) %>円