config/routes.rb
Rails.application.routes.draw do
 
  scope module: :public do
    #URLはpublicを消したいのでpublicのルートはこの中に記述する
    #'指定したいURL' => 'コントローラー名#アクション名', as: 'ルートパス'
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'customers/show'
    get 'customers/information/edit' => 'customers#edit', as: 'customers/edit'
    get 'customers/unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers/update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customers/withdraw'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_item/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/complete' => 'orders#complete', as: 'orders/complete'
    post 'orders/confirm' => 'orders#confirm', as: 'orders/confirm'
    resources :orders, only: [:new, :index, :show, :create]
  end
  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:create, :index, :new, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions:      'admin/sessions'
}
devise_for :customers,skip: [:passwords], controllers: {
  sessions:      'public/sessions',
  registrations: 'public/registrations'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 def add_tax_price
   (self.price * 1.10).floor
 end
  
 def subtotal
      item.add_tax_price*amount
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  belongs_to :item
  belongs_to :customer
  
  def add_tax_price
   (self.price * 1.10).floor
  end
  
  def subtotal
      item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  has_one_attached :image
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def add_tax_price
   (self.price * 1.10).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  def add_tax_price
   (self.price * 1.10).floor
  end
  
  def subtotal
      item.add_tax_price*quantity
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save!
    redirect_to admin_genres_path
  end
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
   private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
   private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = 0
    @postage = 800
    @billing_amount = @postage + @total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <div class="container">
          <ul class="navbar-nav ml-auto">
    <% if customer_signed_in? %>
    ようこそ、<%= current_customer.last_name %>さん！
      <li class="mr-3">
        <%= link_to "マイページ", customers_show_path, class: "btn btn-outline-secondary" %>
      </li>
      <li class="mr-3">
        <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
      </li>
      <li class="mr-3">
        <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
      </li>
    <% elsif admin_signed_in? %>
     <li class="mr-3">
       <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary" %>
     </li>
     <li class="mr-3">
       <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
     </li>
     <li class="mr-3">
       <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary" %>
     </li>
     <li class="mr-3">
       <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary" %>
     </li>
     <li>
       <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
     </li>
    <% else %>
      <li class="mr-3">
        <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
      </li>
      <li class="mr-3">
       <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary" %>
     </li>
      <li class="mr-3">
        <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
      </li>
    <% end %>
      </ul>
     </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>